export const GET_LIST_CUSTOMER_REQUEST_START =
  "GET_LIST_CUSTOMER_REQUEST_START";

export const GET_LIST_CUSTOMER_REQUEST_SUCCEEDED =
  "GET_LIST_CUSTOMER_REQUEST_SUCCEEDED";

export const GET_LIST_CUSTOMER_REQUEST_FAILED =
  "GET_LIST_CUSTOMER_REQUEST_FAILED";
